/**
 * Delivery Entity Configuration
 *
 * Groups location transfers and order fulfillments into a single delivery run.
 * A truck might restock the taproom and deliver orders on the same trip.
 *
 * Lifecycle: planned -> in_transit -> completed (or cancelled from planned/in_transit)
 * delivery_number is auto-generated by a trigger (DEL-YYYYMMDD-NNN format).
 */

import { z } from "zod";
import type { EntityConfig, StateMachineConfig } from "@/types/entity";
import { statesAsOptions } from "@/types/entity";
import { StatusBadge } from "@/components/universal/status-badge";

// =============================================================================
// Types
// =============================================================================

type DeliveryView = {
  id: string;
  delivery_number: string;
  status: string;
  scheduled_date: string | null;
  ship_date: string | null;
  receive_date: string | null;
  driver_name: string | null;
  vehicle: string | null;
  notes: string | null;
  created_by: string | null;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
  // Computed fields from deliveries_with_summary view
  transfer_count: number;
  order_count: number;
  total_stops: number;
}

// =============================================================================
// State Machine
// =============================================================================

const deliveryStates = ["planned", "in_transit", "completed", "cancelled"] as const;

const deliveryTransitions: Record<string, string[]> = {
  planned: ["in_transit", "cancelled"],
  in_transit: ["completed", "cancelled"],
  completed: [],
  cancelled: [],
};

const deliveryStateMachine: StateMachineConfig<DeliveryView> = {
  stateField: "status",
  states: [...deliveryStates],
  initialState: "planned",
  transitions: deliveryTransitions,
  stateDisplay: {
    planned: { label: "Planned", color: "default" },
    in_transit: { label: "In Transit", color: "info" },
    completed: { label: "Completed", color: "success" },
    cancelled: { label: "Cancelled", color: "error" },
  },
};

// Derive status options from state machine (single source of truth)
const statusOptions = statesAsOptions(deliveryStateMachine);

// =============================================================================
// Zod Schema
// =============================================================================

export const deliverySchema = z.object({
  scheduled_date: z.string().nullable().optional(),
  driver_name: z.string().nullable().optional(),
  vehicle: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
});

export type DeliveryFormValues = z.infer<typeof deliverySchema>;

// =============================================================================
// Entity Configuration
// =============================================================================

export const deliveryEntity: EntityConfig<DeliveryView> = {
  // ---------------------------------------------------------------------------
  // Identity
  // ---------------------------------------------------------------------------
  name: "delivery",
  table: "deliveries",
  viewTable: "deliveries_with_summary",
  displayName: "Delivery",
  displayNamePlural: "Deliveries",
  description: "Groups transfers and order fulfillments into delivery runs",
  domain: "inventory",

  // ---------------------------------------------------------------------------
  // List View
  // ---------------------------------------------------------------------------
  listColumns: [
    {
      accessorKey: "delivery_number",
      header: "Delivery #",
      sortable: true,
    },
    {
      accessorKey: "scheduled_date",
      header: "Scheduled",
      sortable: true,
      format: "date",
    },
    {
      accessorKey: "driver_name",
      header: "Driver",
      sortable: true,
    },
    {
      accessorKey: "total_stops",
      header: "Stops",
      sortable: true,
    },
    {
      accessorKey: "status",
      header: "Status",
      sortable: true,
      render: (value) => (
        <StatusBadge
          status={value as string}
          config={deliveryEntity.stateMachine?.stateDisplay}
        />
      ),
    },
  ],

  listFilters: [
    {
      field: "status",
      type: "multiselect",
      label: "Status",
      options: statusOptions,
    },
  ],

  defaultSort: { column: "scheduled_date", direction: "desc" },
  searchableFields: ["delivery_number", "driver_name", "vehicle"],

  // ---------------------------------------------------------------------------
  // Detail View
  // ---------------------------------------------------------------------------
  detailHeader: {
    title: "delivery_number",
    badge: "status",
  },

  // ---------------------------------------------------------------------------
  // Unified Sections (detail + edit)
  // ---------------------------------------------------------------------------
  sections: [
    {
      id: "overview",
      title: "Delivery Details",
      fields: [
        {
          name: "delivery_number",
          label: "Delivery #",
          editable: false,
          colSpan: 6,
        },
        {
          name: "status",
          label: "Status",
          editable: false,
          colSpan: 6,
        },
        {
          name: "scheduled_date",
          label: "Scheduled Date",
          type: "date",
          format: "date",
          colSpan: 6,
        },
        {
          name: "driver_name",
          label: "Driver",
          type: "text",
          colSpan: 6,
        },
        {
          name: "vehicle",
          label: "Vehicle",
          type: "text",
          colSpan: 6,
        },
      ],
    },
    {
      id: "shipping",
      title: "Shipping",
      fields: [
        {
          name: "ship_date",
          label: "Shipped",
          format: "datetime",
          editable: false,
          colSpan: 6,
        },
        {
          name: "receive_date",
          label: "Received",
          format: "datetime",
          editable: false,
          colSpan: 6,
        },
      ],
    },
    {
      id: "summary",
      title: "Stops Summary",
      fields: [
        {
          name: "transfer_count",
          label: "Transfers",
          editable: false,
          colSpan: 4,
        },
        {
          name: "order_count",
          label: "Orders",
          editable: false,
          colSpan: 4,
        },
        {
          name: "total_stops",
          label: "Total Stops",
          editable: false,
          colSpan: 4,
        },
      ],
    },
    {
      id: "notes",
      title: "Notes",
      collapsible: true,
      fields: [
        {
          name: "notes",
          label: "Notes",
          type: "textarea",
          fullWidth: true,
          colSpan: 12,
        },
      ],
    },
  ],

  // ---------------------------------------------------------------------------
  // Form
  // ---------------------------------------------------------------------------
  formSchema: deliverySchema,

  // ---------------------------------------------------------------------------
  // State Machine
  // ---------------------------------------------------------------------------
  stateMachine: deliveryStateMachine,

  // ---------------------------------------------------------------------------
  // Actions
  // ---------------------------------------------------------------------------
  actions: [
    {
      name: "ship",
      label: "Ship",
      icon: "truck",
      type: "button",
      fromStates: ["planned"],
      toState: "in_transit",
    },
    {
      name: "complete",
      label: "Complete",
      icon: "check",
      type: "button",
      fromStates: ["in_transit"],
      toState: "completed",
    },
    {
      name: "cancel",
      label: "Cancel",
      icon: "x",
      type: "dropdown",
      variant: "destructive",
      fromStates: ["planned", "in_transit"],
      toState: "cancelled",
      confirm: true,
    },
  ],

  // ---------------------------------------------------------------------------
  // Relations
  // ---------------------------------------------------------------------------
  relations: [
    {
      name: "transfers",
      entity: "location_transfer",
      type: "hasMany",
      foreignKey: "delivery_id",
      showInDetail: true,
      detailTab: "Transfers",
    },
    {
      name: "orders",
      entity: "order",
      type: "hasMany",
      foreignKey: "delivery_id",
      showInDetail: true,
      detailTab: "Orders",
    },
  ],

  // ---------------------------------------------------------------------------
  // AI Context
  // ---------------------------------------------------------------------------
  queryExamples: [
    "Show planned deliveries",
    "List deliveries for this week",
    "Find deliveries by driver",
    "Show in-transit deliveries",
  ],

  keyFields: ["delivery_number", "status", "scheduled_date", "driver_name"],
};
