/** Approved aliases and historical distributor pricing defaults for Beer Orders imports. */

export const BEER_ORDER_IMPORT_NAMESPACE = "3c39cd42-e9f2-45d0-b33d-d1429e79c7d2";

export const CUSTOMER_ALIASES: Record<string, string> = {
  "sarene east": "Sarene Craft East",
  "sarene craft east": "Sarene Craft East",
  "sarane west": "Sarene Craft West",
  "sarene west": "Sarene Craft West",
  "sarene craft west": "Sarene Craft West",
  "sarene totals": "Sarene Craft Beer",
  "sarene totals pennsylvania": "Sarene Craft Beer",
  "sarene craft beer": "Sarene Craft Beer",
  "lake beverage": "Lake Beverage",
  "lake beverage rochester": "Lake Beverage",
  "hops express": "Hops Express - Hong Kong",
  "hops express hong kong": "Hops Express - Hong Kong",
  "coolship international": "Coolship International - South Korea",
  "coolship international south korea": "Coolship International - South Korea",
  "sixth city": "Sixth City - Ohio",
  "sixth city ohio": "Sixth City - Ohio",
  china: "Odyssey Club - China",
  "odyssey club china": "Odyssey Club - China",
  "unusual holdings": "Unusual Holdings - Japan",
  "unusual holdings japan": "Unusual Holdings - Japan",
  "brew export": "Brew Export - UK",
  "brew export uk": "Brew Export - UK",
  interbeer: "Interbeer - Europe",
  "interbeer europe": "Interbeer - Europe",
};

export const BRAND_ALIASES: Record<string, string> = {
  "african wild dog animal 9": "African Wild Dog",
  "aurantia double": "Aurantia",
  bluejay: "Blue Jay",
  "cardinal bird 2": "Cardinal",
  "ddh rubico": "Rubico II",
  "double lupula eggers": "Double Lupula (Eggers)",
  "eagle animal 8": "Eagle",
  "evergrain collab osprey": "Osprey",
  "great horned owl animal 11 tall trees collab": "Great Horned Owl",
  "hyena animal 6": "Hyena",
  "leopard ultra hopped ale": "Leopard",
  "lion animal 10": "Lion",
  "luminis braserie collab": "Luminis Brassarie Collab",
  "origen ii": "variant:origen-ii",
  "origen iii ultra hopped ale": "Origen III",
  "panther animal 7": "Panther",
  "parabellum offscript collab": "Parabellum",
  "priscus double ipa": "Priscus",
  "pumpkin stout": "Sever",
  "rubico iii ultra hopped ale": "Rubico III",
  "snow leopard animal 12": "Snow Leopard",
  "taupo": "Taupō",
  "taupo ii": "Taupō II",
  "taupo iii": "Taupō II",
  "tides iii": "Tides II",
  vesparo: "Vespero",
  "verus ipa": "Verus",
  vindobana: "Vindobona",
  "white tiger animal 13": "White Tiger",
  zues: "Zeus",
};

export const DEFAULT_TIER_BY_BRAND: Record<string, number> = {
  Akis: 3,
  Akko: 3,
  Aurantia: 5,
  Capax: 5,
  Costilla: 2,
  Crest: 3,
  Dōmbōc: 5,
  "Double Lupula": 5,
  "Double Prismatic": 5,
  Edge: 4,
  Edo: 1,
  Glyphs: 3,
  Gosev: 1,
  Grandar: 2,
  Hades: 6,
  Hanno: 3,
  Harvest: 5,
  Hurron: 5,
  Imara: 5,
  Jantar: 2,
  "Kamo II": 5,
  Lupula: 3,
  Origen: 5,
  Phokas: 3,
  Priscus: 5,
  Prismatic: 3,
  Sever: 5,
  Rein: 1,
  Rooted: 1,
  Rubico: 5,
  "Rubico II": 5,
  Samo: 1,
  Sonnen: 2,
  Stark: 2,
  "Summer Lupula": 3,
  Taupō: 3,
  "Taupō II": 3,
  "Tides II": 3,
  Tides: 3,
  Tribute: 4,
  Tyrus: 5,
  Verus: 3,
  Vespero: 2,
  Vindobona: 2,
  Waves: 5,
  Zeus: 5,
};

export const DOMESTIC_CUSTOMERS = new Set([
  "Sarene Craft East",
  "Sarene Craft West",
  "Sarene Craft Beer",
  "Lake Beverage",
  "Sixth City - Ohio",
]);
