#!/usr/bin/env bun
/**
 * scripts/check-feature-deployment.ts
 *
 * Enforces the split between "code and tests pass" and "the schema this
 * feature needs is applied on the live database" in `docs/feature_list.json`.
 *
 * Why this exists (#654, split out of #440): the tracker had one `state`
 * field covering both facts. F201 read `passing` for twelve days while
 * nothing recorded whether migration 00250 had reached live, and the
 * follow-up recorded it as prose inside `evidence` — which promptly went
 * stale (it embedded a `00250–00259` live-history range that the chain
 * outgrew). Prose is not a mechanism of record, so deployment state is now a
 * structured, machine-checked field and this script is what reads it.
 *
 * Contract enforced per feature entry:
 *
 *   1. `migrations` is REQUIRED on every entry, in exactly one of three
 *      shapes — the third one exists because a blanket backfill of `[]` would
 *      be a lie, and a lie a check blesses is worse than silence:
 *        ["00250_beer_order_imports.sql"]  audited: these migrations
 *        []                                audited: needs no schema change
 *        "unaudited"                       NOT audited — nothing is claimed
 *      Mandatory rather than opt-in so that "nobody remembered the field"
 *      cannot make this gate vacuously pass (the failure mode of #437).
 *      `"unaudited"` entries are counted and named in the output so they stay
 *      visible instead of reading like an audit result; the size of that
 *      backlog is itself ratcheted (see `auditUnauditedBacklog`).
 *   2. Every declared filename must exist in `supabase/migrations/`, and the
 *      list may not repeat one. That is the drift check: a renumbered or
 *      renamed migration (this repo has done both — 00260 → 00266, #545)
 *      fails loudly instead of silently pointing at nothing.
 *   3. If any of the entry's own text names a migration the list omits — or
 *      names one at all while the entry claims `"unaudited"` — that is a
 *      violation. Best-effort corroboration only: the list is the record, and
 *      this tripwire exists so a stale `[]` next to evidence that names
 *      `supabase/migrations/00170_*.sql` cannot pass unnoticed (that is how
 *      F200 surfaced).
 *   4. `state: "passing"` + a non-empty `migrations` list REQUIRES a
 *      `deployment` record. Missing one is the headline failure — a feature
 *      claiming done with nothing recorded about the live database.
 *   5. The `deployment` record accepts only a fixed key set, so nobody can
 *      park an undated parenthetical inside it:
 *        { "state": "live", "observed_live_on": "YYYY-MM-DD",
 *          "verified_by": ["supabase/live-catalog.snapshot.txt", "#NNN", ...] }
 *        { "state": "pending", "pending_since": "YYYY-MM-DD",
 *          "tracking_issue": NNN }
 *
 * What `live` actually verifies, and what it does not:
 *
 *   - `verified_by` MUST cite `supabase/live-catalog.snapshot.txt`, and this
 *     script then OPENS that snapshot: every table, function and trigger the
 *     declared migrations create must appear in it. That is a real check —
 *     it is what caught migration 00139, whose `margin_by_channel`,
 *     `project_finished_goods` and `project_revenue` were in the chain and not
 *     on live (#697; those three have since been dropped from the chain by
 *     00289_drop_orphaned_projection_rpcs.sql, so the discrepancy is closed —
 *     the check that found it is not).
 *   - The snapshot records tables, functions, triggers, policies, RLS
 *     state and CHECK constraints (#865) — NOT views, columns or data. A migration that only adds a column
 *     or creates a view therefore has nothing this script can look for; such a
 *     record is accepted and reported in the summary as "not verifiable from
 *     the snapshot", so its coverage is visible rather than assumed.
 *   - The snapshot is a committed artifact regenerated by `scripts/db-push.sh`,
 *     not a live query. `observed_live_on` is named for what it is: the date
 *     the schema was OBSERVED present, an upper bound on the apply date.
 *   - Other `verified_by` items must be an existing repo-relative path or a
 *     `#NNN` issue/PR reference. `#NNN` is a POINTER for a human, not a proof:
 *     nothing here resolves it, and this script never reaches the network.
 *   - `pending` likewise: `tracking_issue` is not resolved, so `pending_since`
 *     is what stops the record rotting — a pending record older than
 *     PENDING_MAX_AGE_DAYS days fails until someone re-confirms it (bump the
 *     date) or applies the migration.
 *
 * `deployment` records SCHEMA APPLICATION, not that the feature was exercised
 * against production. Functional verification stays in `verification` /
 * `last_verified` (see `verification_conventions` in the tracker).
 *
 * Exit codes (mirroring `scripts/verify-feature.sh`'s manual-receipt path,
 * rather than inventing a new severity):
 *   0  every entry satisfies the contract
 *   2  a feature id was passed and no such entry exists
 *   4  UNVERIFIED — at least one entry violates the contract
 *
 * Usage:
 *   bun run scripts/check-feature-deployment.ts          # whole tracker
 *   bun run scripts/check-feature-deployment.ts F201     # one entry
 *   make check-deploy-state
 */

import { existsSync, readFileSync, readdirSync } from "node:fs";

/** The one receipt this script can actually check a `live` record against. */
export const LIVE_CATALOG_SNAPSHOT = "supabase/live-catalog.snapshot.txt";
/** Sentinel for "this entry's schema dependencies have not been audited". */
export const UNAUDITED = "unaudited";
/** A `pending` record must be re-confirmed at least this often. */
export const PENDING_MAX_AGE_DAYS = 90;

/** One `features[]` entry, as loosely typed as the JSON actually is. */
export type FeatureEntry = {
  id?: unknown;
  state?: unknown;
  migrations?: unknown;
  deployment?: unknown;
  user_visible_behavior?: unknown;
  verification?: unknown;
  evidence?: unknown;
  notes?: unknown;
};

/** A catalog object a migration creates, in the shape the snapshot records. */
export type CatalogObject = { kind: "table" | "function" | "trigger"; name: string };

/** Everything the audit needs from the filesystem and the clock. */
export type AuditContext = {
  /** Filenames present in `supabase/migrations/`. */
  migrationFiles: readonly string[];
  /** SQL text of a migration, by filename. Only called for declared names. */
  readMigration: (name: string) => string;
  /** Lines of `supabase/live-catalog.snapshot.txt`. */
  liveCatalog: readonly string[];
  /** Does this repo-relative path exist? */
  pathExists: (repoRelativePath: string) => boolean;
  /** Today as `YYYY-MM-DD`; injected so the date checks are testable. */
  today: string;
};

/** What the run covered — printed, so an empty audit cannot read as a full one. */
export type AuditStats = {
  checked: number;
  /** Entries audited as needing no schema change (`[]`). */
  noSchema: number;
  /** Entries that declare `"unaudited"` — nothing is claimed about them. */
  unaudited: number;
  /** Entries with a non-empty `migrations` list. */
  migrationBacked: number;
  live: number;
  /** `live` records whose migrations' objects were found in the snapshot. */
  liveSnapshotVerified: number;
  /** `live` records whose migrations create nothing the snapshot records. */
  liveUnverifiable: number;
  pending: number;
};

export type AuditResult = { violations: string[]; stats: AuditStats };

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;
const ISSUE_REF = /^#[1-9]\d*$/;
/** `supabase/migrations/00250_beer_order_imports.sql` inside free text. */
const MIGRATION_PATH = /supabase\/migrations\/(\d{5}_[A-Za-z0-9_.-]+\.sql)/g;
/** `migration 00250` / `migrations 00250` inside free text. */
const MIGRATION_NUMBER = /\bmigrations?\s+(\d{5})\b/gi;

const LIVE_KEYS = ["state", "observed_live_on", "verified_by"] as const;
const PENDING_KEYS = ["state", "pending_since", "tracking_issue"] as const;

function isRealIsoDate(value: string): boolean {
  if (!ISO_DATE.test(value)) return false;
  const parsed = new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value;
}

function daysBetween(from: string, to: string): number {
  const ms = Date.parse(`${to}T00:00:00Z`) - Date.parse(`${from}T00:00:00Z`);
  return Math.round(ms / 86_400_000);
}

/**
 * A repo-relative path that cannot escape the repo. `../../../etc/hosts`
 * exists on most machines; it is not evidence about this deployment.
 */
function isSafeRepoPath(path: string): boolean {
  return !path.startsWith("/") && !path.split("/").includes("..");
}

function freeText(feature: FeatureEntry): string {
  return [feature.user_visible_behavior, feature.verification, feature.evidence, feature.notes]
    .filter((v): v is string => typeof v === "string")
    .join("\n");
}

/**
 * Tables, functions and triggers a migration creates — the object kinds the
 * live-catalog snapshot records. Views, columns, indexes, types and data are
 * deliberately not extracted: the snapshot does not carry them, so claiming to
 * check them would be theatre.
 */
export function createdCatalogObjects(sql: string): CatalogObject[] {
  const stripped = sql.replace(/\/\*[\s\S]*?\*\//g, " ").replace(/--[^\n]*/g, " ");
  const objects: CatalogObject[] = [];
  const add = (kind: CatalogObject["kind"], name: string): void => {
    const lower = name.toLowerCase();
    if (!objects.some((o) => o.kind === kind && o.name === lower)) objects.push({ kind, name: lower });
  };

  for (const m of stripped.matchAll(
    /create\s+table\s+(?:if\s+not\s+exists\s+)?(?:public\.)?"?([A-Za-z0-9_]+)"?/gi,
  )) {
    add("table", m[1]);
  }
  for (const m of stripped.matchAll(
    /create\s+(?:or\s+replace\s+)?function\s+(?:public\.)?"?([A-Za-z0-9_]+)"?\s*\(/gi,
  )) {
    add("function", m[1]);
  }
  for (const m of stripped.matchAll(
    /create\s+(?:or\s+replace\s+)?trigger\s+"?([A-Za-z0-9_]+)"?/gi,
  )) {
    add("trigger", m[1]);
  }
  return objects;
}

/** Is this object present in the committed live-catalog snapshot? */
export function catalogHas(catalog: readonly string[], object: CatalogObject): boolean {
  if (object.kind === "table") return catalog.includes(`TABLE|${object.name}`);
  const prefix = object.kind === "function" ? `FUNC|${object.name}(` : `TRIG|${object.name}|`;
  return catalog.some((line) => line.startsWith(prefix));
}

/**
 * Audit deployment records. `violations` is empty when the entries satisfy the
 * contract described in the file header; `stats` says what was actually
 * covered, so a run over entries that claim nothing cannot print like an audit.
 */
export function auditFeatureDeployment(
  features: readonly FeatureEntry[],
  ctx: AuditContext,
): AuditResult {
  const violations: string[] = [];
  const stats: AuditStats = {
    checked: features.length,
    noSchema: 0,
    unaudited: 0,
    migrationBacked: 0,
    live: 0,
    liveSnapshotVerified: 0,
    liveUnverifiable: 0,
    pending: 0,
  };

  for (const feature of features) {
    const id = typeof feature.id === "string" && feature.id ? feature.id : "<entry with no id>";
    const fail = (message: string): void => void violations.push(`${id}: ${message}`);
    const text = freeText(feature);
    const namesAMigration =
      [...text.matchAll(MIGRATION_PATH)].length > 0 || [...text.matchAll(MIGRATION_NUMBER)].length > 0;

    // 1. `migrations` is mandatory, in one of three shapes.
    if (feature.migrations === UNAUDITED) {
      stats.unaudited++;
      if (feature.deployment !== undefined) {
        fail(
          `declares "migrations": "${UNAUDITED}" but carries a "deployment" record — a ` +
            "deployment record must be anchored to migrations the entry actually declares.",
        );
      }
      if (namesAMigration) {
        fail(
          `declares "migrations": "${UNAUDITED}" but its own text names a migration, so it is ` +
            "auditable right now — list the migration(s) it depends on.",
        );
      }
      continue;
    }
    if (
      !Array.isArray(feature.migrations) ||
      feature.migrations.some((m) => typeof m !== "string" || m.trim() === "")
    ) {
      fail(
        'missing or malformed "migrations" — every entry must declare the migration filenames ' +
          'it depends on, e.g. ["00250_beer_order_imports.sql"]; [] when it needs no schema ' +
          `change; "${UNAUDITED}" when nobody has established which it is.`,
      );
      continue;
    }
    const migrations = feature.migrations as string[];

    // 2. Declared migrations must exist in the chain, exactly once each.
    for (const [index, name] of migrations.entries()) {
      if (!ctx.migrationFiles.includes(name)) {
        fail(
          `declares migration "${name}" but supabase/migrations/${name} does not exist — ` +
            "the chain was renumbered or renamed, or the entry is stale.",
        );
      }
      if (migrations.indexOf(name) !== index) {
        fail(`declares migration "${name}" more than once.`);
      }
    }

    // 3. Corroboration: the entry's own text must not name a migration the
    //    list omits.
    for (const match of text.matchAll(MIGRATION_PATH)) {
      const name = match[1];
      if (!migrations.includes(name)) {
        fail(`text references supabase/migrations/${name} but "migrations" does not list it.`);
      }
    }
    for (const match of text.matchAll(MIGRATION_NUMBER)) {
      const number = match[1];
      if (!migrations.some((name) => name.startsWith(`${number}_`))) {
        fail(`text references migration ${number} but "migrations" does not list it.`);
      }
    }

    // 4. Is a deployment record required / allowed?
    const record = feature.deployment;
    if (migrations.length === 0) {
      stats.noSchema++;
      if (record !== undefined) {
        fail(
          'has a "deployment" record but declares no migrations — a deployment record must ' +
            "be anchored to at least one migration.",
        );
      }
      continue;
    }
    stats.migrationBacked++;
    if (record === undefined) {
      if (feature.state === "passing") {
        fail(
          `state "passing" with migrations [${migrations.join(", ")}] and no "deployment" ` +
            'record. Add {"state":"live","observed_live_on":"YYYY-MM-DD","verified_by":[...]} ' +
            'once an operator has applied it, or {"state":"pending","pending_since":' +
            '"YYYY-MM-DD","tracking_issue":NNN} while it is waiting.',
        );
      }
      continue;
    }

    // 5. Shape of the deployment record.
    if (typeof record !== "object" || record === null || Array.isArray(record)) {
      fail('"deployment" must be an object.');
      continue;
    }
    const fields = record as Record<string, unknown>;
    const deploymentState = fields.state;
    if (deploymentState !== "live" && deploymentState !== "pending") {
      fail('deployment.state must be "live" or "pending".');
      continue;
    }

    const allowed: readonly string[] = deploymentState === "live" ? LIVE_KEYS : PENDING_KEYS;
    for (const key of Object.keys(fields)) {
      if (!allowed.includes(key)) {
        fail(
          `deployment has unexpected key "${key}" for state "${deploymentState}" (allowed: ` +
            `${allowed.join(", ")}). The deployment record is structured data — narrative ` +
            "belongs in `evidence`.",
        );
      }
    }

    if (deploymentState === "live") {
      stats.live++;
      auditLiveRecord(id, migrations, fields, ctx, stats, fail);
    } else {
      stats.pending++;
      auditPendingRecord(fields, ctx, fail);
    }
  }

  return { violations, stats };
}

/** `live`: a dated observation plus receipts, one of which is machine-checked. */
function auditLiveRecord(
  id: string,
  migrations: readonly string[],
  fields: Record<string, unknown>,
  ctx: AuditContext,
  stats: AuditStats,
  fail: (message: string) => void,
): void {
  const observedOn = fields.observed_live_on;
  if (typeof observedOn !== "string" || !isRealIsoDate(observedOn)) {
    fail(
      'deployment.state "live" requires "observed_live_on": "YYYY-MM-DD" (a real date) — the ' +
        "date the schema was observed present on live, which is an upper bound on the apply date.",
    );
  } else if (observedOn > ctx.today) {
    fail(`deployment.observed_live_on ${observedOn} is in the future (today is ${ctx.today}).`);
  }

  const verifiedBy = fields.verified_by;
  if (!Array.isArray(verifiedBy) || verifiedBy.length === 0) {
    fail(
      'deployment.state "live" requires a non-empty "verified_by" array containing ' +
        `"${LIVE_CATALOG_SNAPSHOT}" and, optionally, "#NNN" issue/PR pointers.`,
    );
    return;
  }

  for (const [index, item] of verifiedBy.entries()) {
    if (typeof item !== "string" || item.trim() === "") {
      fail("deployment.verified_by entries must be non-empty strings.");
      continue;
    }
    if (verifiedBy.indexOf(item) !== index) {
      fail(`deployment.verified_by lists "${item}" more than once.`);
    }
    if (ISSUE_REF.test(item)) continue;
    if (!isSafeRepoPath(item)) {
      fail(
        `deployment.verified_by entry "${item}" is not a repo-relative path — an absolute path ` +
          "or one that escapes the repo is not evidence about this repo's deployment.",
      );
    } else if (!ctx.pathExists(item)) {
      fail(
        `deployment.verified_by entry "${item}" is neither an existing repo-relative path ` +
          'nor a "#NNN" issue/PR reference.',
      );
    }
  }

  if (!verifiedBy.includes(LIVE_CATALOG_SNAPSHOT)) {
    fail(
      `deployment.state "live" must cite "${LIVE_CATALOG_SNAPSHOT}" in "verified_by" — it is ` +
        "the only receipt this check can verify. A `#NNN` reference is a pointer for a human; " +
        "nothing resolves it.",
    );
    return;
  }

  // The actual verification: open the snapshot and look for the objects the
  // declared migrations create.
  const missing: string[] = [];
  let looked = 0;
  for (const name of migrations) {
    if (!ctx.migrationFiles.includes(name)) continue; // already reported
    const objects = createdCatalogObjects(ctx.readMigration(name));
    looked += objects.length;
    for (const object of objects) {
      if (!catalogHas(ctx.liveCatalog, object)) missing.push(`${name}: ${object.kind} ${object.name}`);
    }
  }
  if (missing.length > 0) {
    fail(
      `deployment.state "live" but ${missing.length} object(s) the declared migration(s) create ` +
        `are absent from ${LIVE_CATALOG_SNAPSHOT}: ${missing.join("; ")}. Either the migration ` +
        "is not (fully) applied on live — record `pending` and open an issue — or a later " +
        "migration renamed or dropped the object and this entry's anchor needs re-auditing.",
    );
  } else if (looked === 0) {
    // A column-add / view-only / data-only migration. Nothing to look for.
    stats.liveUnverifiable++;
  } else {
    stats.liveSnapshotVerified++;
  }
}

/** `pending`: an issue pointer plus a date that has to be re-confirmed. */
function auditPendingRecord(
  fields: Record<string, unknown>,
  ctx: AuditContext,
  fail: (message: string) => void,
): void {
  const issue = fields.tracking_issue;
  if (typeof issue !== "number" || !Number.isInteger(issue) || issue <= 0) {
    fail(
      'deployment.state "pending" requires "tracking_issue": <issue number>. This check does ' +
        "not resolve it (it never reaches the network) — it is a pointer for a human.",
    );
  }

  const since = fields.pending_since;
  if (typeof since !== "string" || !isRealIsoDate(since)) {
    fail(
      'deployment.state "pending" requires "pending_since": "YYYY-MM-DD" — the dated receipt ' +
        "is what stops an un-applied migration rotting unnoticed, since nothing here can tell " +
        "whether the tracking issue is still open.",
    );
    return;
  }
  if (since > ctx.today) {
    fail(`deployment.pending_since ${since} is in the future (today is ${ctx.today}).`);
    return;
  }
  const age = daysBetween(since, ctx.today);
  if (age > PENDING_MAX_AGE_DAYS) {
    fail(
      `deployment has been "pending" since ${since} (${age} days, limit ` +
        `${PENDING_MAX_AGE_DAYS}). Apply the migration, or re-confirm it is still pending and ` +
        "bump `pending_since`.",
    );
  }
}

/**
 * The `"unaudited"` backlog is ratcheted: `deployment_conventions
 * .unaudited_backlog.count` must equal the number of entries that declare the
 * sentinel. Auditing one requires lowering the number; adding one requires
 * raising it, which is visible in review rather than silent.
 */
export function auditUnauditedBacklog(actual: number, backlog: unknown): string[] {
  const where = "docs/feature_list.json deployment_conventions.unaudited_backlog";
  if (typeof backlog !== "object" || backlog === null || Array.isArray(backlog)) {
    return [`${where} is missing — it must be {"count": N, "tracking_issue": NNN}.`];
  }
  const fields = backlog as Record<string, unknown>;
  const violations: string[] = [];
  const { count, tracking_issue: issue } = fields;

  if (typeof issue !== "number" || !Number.isInteger(issue) || issue <= 0) {
    violations.push(`${where}.tracking_issue must be the issue number the audit is tracked by.`);
  }
  if (typeof count !== "number" || !Number.isInteger(count) || count < 0) {
    violations.push(`${where}.count must be a non-negative integer.`);
  } else if (count !== actual) {
    violations.push(
      `${where}.count is ${count} but ${actual} entr${actual === 1 ? "y declares" : "ies declare"} ` +
        `"migrations": "${UNAUDITED}". Set it to ${actual}` +
        (actual > count ? " — and say in the PR why the backlog grew." : "."),
    );
  }
  for (const key of Object.keys(fields)) {
    if (key !== "count" && key !== "tracking_issue") {
      violations.push(`${where} has unexpected key "${key}" (allowed: count, tracking_issue).`);
    }
  }
  return violations;
}

/** Multi-line report of what the run covered. Never says "all" of nothing. */
function summarize(stats: AuditStats, backlogIssue: string): string {
  const lines = [
    `OK: ${stats.checked} feature entr${stats.checked === 1 ? "y" : "ies"} checked`,
    `    ${stats.migrationBacked} migration-backed — ${stats.live} live ` +
      `(${stats.liveSnapshotVerified} verified against ${LIVE_CATALOG_SNAPSHOT}, ` +
      `${stats.liveUnverifiable} not verifiable from it), ${stats.pending} pending`,
    `    ${stats.noSchema} audited as needing no schema change`,
  ];
  if (stats.unaudited > 0) {
    lines.push(
      `    ${stats.unaudited} NOT AUDITED ("migrations": "${UNAUDITED}") — nothing is claimed ` +
        `about ${stats.unaudited === 1 ? "it" : "them"}${backlogIssue}`,
    );
  }
  return lines.join("\n");
}

function main(): void {
  const repoRoot = new URL("..", import.meta.url);
  const only = process.argv[2];

  const tracker = JSON.parse(
    readFileSync(new URL("docs/feature_list.json", repoRoot), "utf8"),
  ) as { features: FeatureEntry[]; deployment_conventions?: Record<string, unknown> };

  const features = only ? tracker.features.filter((f) => f.id === only) : tracker.features;
  if (only && features.length === 0) {
    console.error(`ERROR: feature '${only}' not found in docs/feature_list.json`);
    process.exit(2);
  }

  const { violations, stats } = auditFeatureDeployment(features, {
    migrationFiles: readdirSync(new URL("supabase/migrations/", repoRoot)).filter((name) =>
      name.endsWith(".sql"),
    ),
    readMigration: (name) =>
      readFileSync(new URL(`supabase/migrations/${name}`, repoRoot), "utf8"),
    liveCatalog: readFileSync(new URL(LIVE_CATALOG_SNAPSHOT, repoRoot), "utf8").split("\n"),
    pathExists: (path) => isSafeRepoPath(path) && existsSync(new URL(path, repoRoot)),
    today: new Date().toISOString().slice(0, 10),
  });

  // The backlog ratchet is a whole-tracker property; a scoped run sees one entry.
  const backlog = tracker.deployment_conventions?.unaudited_backlog;
  if (!only) violations.push(...auditUnauditedBacklog(stats.unaudited, backlog));

  if (violations.length === 0) {
    const issue =
      typeof (backlog as { tracking_issue?: unknown } | undefined)?.tracking_issue === "number"
        ? `, tracked by #${(backlog as { tracking_issue: number }).tracking_issue}`
        : "";
    console.log(summarize(stats, issue));
    process.exit(0);
  }

  console.error(
    `UNVERIFIED: ${violations.length} deployment-record problem(s) in docs/feature_list.json:\n`,
  );
  for (const violation of violations) console.error(`  ${violation}`);
  console.error(
    "\nFix: `migrations` lists what the feature needs applied; `deployment` records whether\n" +
      "     it is applied. See `deployment_conventions` in docs/feature_list.json and\n" +
      '     AGENTS.md "Work-in-progress rule".',
  );
  process.exit(4);
}

// Run as a script, skip under vitest. Deliberately fail-CLOSED: an argv-shape
// predicate would silently do nothing if the file were renamed or invoked
// differently, and a gate that quietly exits 0 is worse than no gate.
// `import.meta.main` (used by .github/scripts/loop-scoreboard.ts) is not in the
// ambient ImportMeta type, and unlike `.github/` — which TypeScript's wildcard
// include skips because it is a dotted directory — `scripts/` IS typechecked,
// so this tree cannot use it.
if (!process.env.VITEST) main();
