-- Fix BJCP styles that already existed
-- Updates is_bjcp flag and vital stats for BJCP style names

-- First, ensure the column exists
ALTER TABLE beer_styles ADD COLUMN IF NOT EXISTS is_bjcp boolean DEFAULT false;

-- Update existing styles to mark as BJCP and set their vital stats
-- Using ON CONFLICT to upsert

-- Delete all existing and re-insert with proper data
DELETE FROM beer_styles WHERE name IN (
  'American Light Lager', 'American Lager', 'Cream Ale', 'American Wheat Beer',
  'International Pale Lager', 'International Amber Lager', 'International Dark Lager',
  'Czech Pale Lager', 'Czech Premium Pale Lager', 'Czech Amber Lager', 'Czech Dark Lager',
  'Munich Helles', 'Festbier', 'Helles Bock', 'German Leichtbier', 'Kölsch',
  'German Helles Exportbier', 'German Pils', 'Märzen', 'Rauchbier', 'Dunkles Bock',
  'Vienna Lager', 'Altbier', 'Kellerbier', 'Munich Dunkel', 'Schwarzbier',
  'Doppelbock', 'Eisbock', 'Baltic Porter', 'Weissbier', 'Dunkles Weissbier',
  'Weizenbock', 'Ordinary Bitter', 'Best Bitter', 'Strong Bitter', 'British Golden Ale',
  'Australian Sparkling Ale', 'English IPA', 'Dark Mild', 'British Brown Ale',
  'English Porter', 'Scottish Light', 'Scottish Heavy', 'Scottish Export',
  'Irish Red Ale', 'Irish Stout', 'Irish Extra Stout', 'Sweet Stout', 'Oatmeal Stout',
  'Tropical Stout', 'Foreign Extra Stout', 'British Strong Ale', 'Old Ale',
  'Wee Heavy', 'English Barleywine', 'Blonde Ale', 'American Pale Ale',
  'American Amber Ale', 'California Common', 'American Brown Ale', 'American Porter',
  'American Stout', 'Imperial Stout', 'American IPA', 'Specialty IPA', 'Hazy IPA',
  'Double IPA', 'American Strong Ale', 'American Barleywine', 'Wheatwine',
  'Berliner Weisse', 'Flanders Red Ale', 'Oud Bruin', 'Lambic', 'Gueuze',
  'Fruit Lambic', 'Gose', 'Witbier', 'Belgian Pale Ale', 'Bière de Garde',
  'Belgian Blond Ale', 'Saison', 'Belgian Golden Strong Ale', 'Belgian Single',
  'Belgian Dubbel', 'Belgian Tripel', 'Belgian Dark Strong Ale', 'Trappist Single',
  'Mixed-Fermentation Sour Beer', 'Wild Specialty Beer', 'Fruit Beer',
  'Fruit and Spice Beer', 'Specialty Fruit Beer', 'Grape Ale', 'Spice, Herb, or Vegetable Beer',
  'Autumn Seasonal Beer', 'Winter Seasonal Beer', 'Alternative Grain Beer',
  'Alternative Sugar Beer', 'Classic Style Smoked Beer', 'Specialty Smoked Beer',
  'Commercial Specialty Beer', 'Mixed-Style Beer', 'Experimental Beer',
  'Dorada Pampeana', 'IPA Argenta', 'Italian Grape Ale', 'Catharina Sour',
  'New Zealand Pilsner'
);

-- Now insert fresh BJCP data
INSERT INTO beer_styles (name, category, description, og_min, og_max, fg_min, fg_max, abv_min, abv_max, ibu_min, ibu_max, srm_min, srm_max, is_bjcp)
VALUES
  ('American Light Lager', 'Standard American Beer', 'A highly carbonated, very light-bodied, nearly flavorless lager designed to be consumed very cold. Very refreshing and thirst-quenching.', 1.028, 1.04, 0.998, 1.008, 2.8, 4.2, 8, 12, 2, 3, true),
  ('American Lager', 'Standard American Beer', 'A very pale, highly-carbonated, light-bodied, well-attenuated lager with a very neutral flavor profile and low bitterness. Served very cold, it can be a very refreshing and thirst-quenching drink.', 1.04, 1.05, 1.004, 1.01, 4.2, 5.3, 8, 18, 2, 3.5, true),
  ('Cream Ale', 'Standard American Beer', 'A clean, well-attenuated, highly carbonated, flavorful American "lawnmower" beer. Easily drinkable, smooth, and refreshing, with more character than typical American lagers, yet still subtle and restrained.', 1.042, 1.055, 1.006, 1.012, 4.2, 5.6, 8, 20, 2, 5, true),
  ('American Wheat Beer', 'Standard American Beer', 'A pale, refreshing grainy, doughy, or bready wheat beer with a clean fermentation profile and a variable hop character and bitterness. Its lighter body and higher carbonation contribute to its easy-drinking nature.', 1.04, 1.055, 1.008, 1.013, 4, 5.5, 15, 30, 3, 6, true),
  ('International Pale Lager', 'International Lager', 'A highly-attenuated pale lager without strong flavors, typically well-balanced and highly carbonated. Served cold, it is refreshing and thirst-quenching.', 1.042, 1.05, 1.008, 1.012, 4.5, 6, 18, 25, 2, 6, true),
  ('International Amber Lager', 'International Lager', 'A smooth, easily-drinkable, malty amber lager with a flavorful caramel or toast character. Usually fairly well-attenuated, often with an adjunct quality and restrained bitterness.', 1.042, 1.055, 1.008, 1.014, 4.5, 6, 8, 25, 6, 14, true),
  ('International Dark Lager', 'International Lager', 'A darker, richer, and somewhat sweeter version of international pale lager with a little more body and flavor, but equally restrained in bitterness.', 1.044, 1.056, 1.008, 1.012, 4.2, 6, 8, 20, 14, 30, true),
  ('Czech Pale Lager', 'Czech Lager', 'A lighter-bodied, rich, refreshing, hoppy, bitter pale Czech lager having the familiar flavors of the stronger Czech Premium Pale Lager (Pilsner-type) beer but in a lower alcohol, lighter-bodied, and slightly less intense format.', 1.028, 1.044, 1.008, 1.014, 3, 4.1, 20, 35, 3, 6, true),
  ('Czech Premium Pale Lager', 'Czech Lager', 'A refreshing pale Czech lager with considerable malt and hop character and a long finish.', 1.044, 1.06, 1.013, 1.017, 4.2, 5.8, 30, 45, 3.5, 6, true),
  ('Czech Amber Lager', 'Czech Lager', 'A malty amber Czech lager with a hop character that can vary from low to quite significant.', 1.044, 1.06, 1.013, 1.017, 4.4, 5.8, 20, 35, 10, 16, true),
  ('Czech Dark Lager', 'Czech Lager', 'A rich, dark, malty Czech lager with a roast character that can vary from almost absent to quite prominent.', 1.044, 1.06, 1.013, 1.017, 4.4, 5.8, 18, 34, 17, 35, true),
  ('Munich Helles', 'Pale Malty European Lager', 'A gold-colored German lager with a smooth, malty flavor and a soft, dry finish.', 1.044, 1.048, 1.006, 1.012, 4.7, 5.4, 16, 22, 3, 5, true),
  ('Festbier', 'Pale Malty European Lager', 'A smooth, clean, pale German lager with a moderately strong malty flavor and a light hop character.', 1.054, 1.057, 1.01, 1.012, 5.8, 6.3, 18, 25, 4, 6, true),
  ('Helles Bock', 'Pale Malty European Lager', 'A relatively pale, strong, malty German lager with a nicely attenuated finish that enhances drinkability.', 1.064, 1.072, 1.011, 1.018, 6.3, 7.4, 23, 35, 6, 9, true),
  ('German Leichtbier', 'Pale Bitter European Beer', 'A pale, highly-attenuated, light-bodied German lager with lower alcohol and calories than standard-strength beers.', 1.026, 1.034, 1.006, 1.01, 2.4, 3.6, 15, 28, 1.5, 4, true),
  ('Kölsch', 'Pale Bitter European Beer', 'A subtle, brilliantly clear, pale beer with a delicate balance of malt, fruit, and hop character.', 1.044, 1.05, 1.007, 1.011, 4.4, 5.2, 18, 30, 3.5, 5, true),
  ('German Helles Exportbier', 'Pale Bitter European Beer', 'A golden German lager balancing a smooth malty profile with a bitter, hoppy character.', 1.05, 1.058, 1.008, 1.015, 5, 6, 20, 30, 4, 6, true),
  ('German Pils', 'Pale Bitter European Beer', 'A pale, dry, bitter German lager featuring a prominent hop aroma. Crisp, clean, and refreshing.', 1.044, 1.05, 1.008, 1.013, 4.4, 5.2, 22, 40, 2, 4, true),
  ('Märzen', 'Amber Malty European Lager', 'An amber, malty German lager with a clean, rich, toasty, bready malt flavor.', 1.054, 1.06, 1.01, 1.014, 5.6, 6.3, 18, 24, 8, 17, true),
  ('Rauchbier', 'Amber Malty European Lager', 'A beechwood-smoked, malty, amber German lager.', 1.05, 1.057, 1.012, 1.016, 4.8, 6, 20, 30, 12, 22, true),
  ('Dunkles Bock', 'Amber Malty European Lager', 'A strong, dark, malty German lager beer that emphasizes the malty-rich and somewhat toasty qualities.', 1.064, 1.072, 1.013, 1.019, 6.3, 7.2, 20, 27, 14, 22, true),
  ('Vienna Lager', 'Amber Malty European Lager', 'A moderate-strength amber lager with a soft, smooth maltiness and moderate bitterness.', 1.048, 1.055, 1.01, 1.014, 4.7, 5.5, 18, 30, 9, 15, true),
  ('Altbier', 'Pale Bitter European Beer', 'A well-balanced, well-attenuated, bitter yet malty, clean, and smooth, amber to copper-colored German beer.', 1.044, 1.052, 1.008, 1.014, 4.3, 5.5, 25, 50, 9, 17, true),
  ('Munich Dunkel', 'Dark Malty European Lager', 'A traditional malty brown lager from Munich, Germany.', 1.048, 1.056, 1.01, 1.016, 4.5, 5.6, 18, 28, 17, 28, true),
  ('Schwarzbier', 'Dark Malty European Lager', 'A dark German lager that balances roasted yet smooth malt flavors with moderate hop bitterness.', 1.046, 1.052, 1.01, 1.016, 4.4, 5.4, 20, 35, 19, 30, true),
  ('Doppelbock', 'Strong European Beer', 'A strong, rich, and very malty German lager that can have both pale and dark variants.', 1.072, 1.112, 1.016, 1.024, 7, 10, 16, 26, 6, 25, true),
  ('Eisbock', 'Strong European Beer', 'A strong, full-bodied, rich, and malty dark German lager often with a viscous quality.', 1.078, 1.12, 1.02, 1.035, 9, 14, 25, 35, 17, 30, true),
  ('Baltic Porter', 'Strong European Beer', 'A Baltic Porter has the malt flavors reminiscent of an English brown porter, but with a higher OG and alcohol content.', 1.06, 1.09, 1.016, 1.024, 6.5, 9.5, 20, 40, 17, 30, true),
  ('Weissbier', 'German Wheat Beer', 'A pale, refreshing German wheat beer with high carbonation, dry finish, a fluffy mouthfeel, and a distinctive banana-and-clove yeast character.', 1.044, 1.053, 1.008, 1.014, 4.3, 5.6, 8, 15, 2, 6, true),
  ('Dunkles Weissbier', 'German Wheat Beer', 'A moderately dark German wheat beer with a distinctive banana-and-clove yeast character, supported by a toasted bread or caramel malt flavor.', 1.044, 1.057, 1.008, 1.014, 4.3, 5.6, 10, 18, 14, 23, true),
  ('Weizenbock', 'German Wheat Beer', 'A strong, malty, fruity, wheat-based ale combining the best malt and yeast flavors of a Weissbier with the malty richness, strength, and body of a Bock.', 1.064, 1.09, 1.015, 1.022, 6.5, 9, 15, 30, 6, 25, true),
  ('Ordinary Bitter', 'British Bitter', 'Low gravity, low alcohol levels, and low carbonation make this an easy-drinking session beer.', 1.03, 1.039, 1.007, 1.011, 3.2, 3.8, 25, 35, 8, 14, true),
  ('Best Bitter', 'British Bitter', 'A flavorful, yet refreshing, session beer. Some examples can be more malt balanced, but this should not override the overall bitter impression.', 1.04, 1.048, 1.008, 1.012, 3.8, 4.6, 25, 40, 8, 16, true),
  ('Strong Bitter', 'British Bitter', 'An average-strength to moderately-strong British bitter ale. The balance may vary between fairly even between malt and hops to somewhat bitter.', 1.048, 1.06, 1.01, 1.016, 4.6, 6.2, 30, 50, 8, 18, true),
  ('British Golden Ale', 'Pale Commonwealth Beer', 'A hop-forward, average-strength to moderately-strong pale bitter.', 1.038, 1.053, 1.006, 1.012, 3.8, 5, 20, 45, 2, 5, true),
  ('Australian Sparkling Ale', 'Pale Commonwealth Beer', 'A well-balanced, pale, highly-carbonated, refreshing ale suitable for drinking in a hot climate.', 1.038, 1.05, 1.004, 1.006, 4.5, 6, 20, 35, 4, 7, true),
  ('English IPA', 'British Bitter', 'A hoppy, moderately-strong, very well-attenuated pale British ale with a dry finish and a hoppy aroma and flavor.', 1.05, 1.07, 1.01, 1.015, 5, 7.5, 40, 60, 6, 14, true),
  ('Dark Mild', 'Brown British Beer', 'A dark, low-gravity, malt-focused British session ale readily suited to drinking in quantity.', 1.03, 1.038, 1.008, 1.013, 3, 3.8, 10, 25, 12, 25, true),
  ('British Brown Ale', 'Brown British Beer', 'A malty, brown caramel-centric British ale without the roasted flavors of a Porter.', 1.04, 1.052, 1.008, 1.013, 4.2, 5.9, 20, 30, 12, 22, true),
  ('English Porter', 'Porter', 'A moderate-strength brown beer with a restrained roasty character and bitterness.', 1.04, 1.052, 1.008, 1.014, 4, 5.4, 18, 35, 20, 30, true),
  ('Scottish Light', 'Scottish Ale', 'A malt-focused, generally caramelly beer with perhaps a few esters and occasionally a butterscotch aftertaste.', 1.03, 1.035, 1.01, 1.013, 2.5, 3.2, 10, 20, 17, 25, true),
  ('Scottish Heavy', 'Scottish Ale', 'A malt-focused, generally caramelly beer with perhaps a few esters and occasionally a butterscotch aftertaste.', 1.035, 1.04, 1.01, 1.015, 3.2, 3.9, 10, 20, 12, 20, true),
  ('Scottish Export', 'Scottish Ale', 'A malt-focused, generally caramelly beer with perhaps a few esters and occasionally a butterscotch aftertaste.', 1.04, 1.06, 1.01, 1.016, 3.9, 6, 15, 30, 12, 20, true),
  ('Irish Red Ale', 'Irish Beer', 'An easy-drinking pint, often with subtle flavors. Slightly malty in the balance sometimes with an initial soft toffee or caramel sweetness.', 1.036, 1.046, 1.01, 1.014, 3.8, 5, 18, 28, 9, 14, true),
  ('Irish Stout', 'Irish Beer', 'A black beer with a pronounced roasted flavor, often similar to coffee.', 1.036, 1.044, 1.007, 1.011, 4, 4.5, 25, 45, 25, 40, true),
  ('Irish Extra Stout', 'Irish Beer', 'A fuller-bodied black beer with a pronounced roasted flavor, often similar to coffee and dark chocolate.', 1.052, 1.062, 1.01, 1.014, 5, 6.5, 35, 50, 25, 40, true),
  ('Sweet Stout', 'Stout', 'A very dark, sweet, full-bodied, slightly roasty stout that can suggest coffee-and-cream, or sweetened espresso.', 1.044, 1.06, 1.012, 1.024, 4, 6, 20, 40, 30, 40, true),
  ('Oatmeal Stout', 'Stout', 'A dark, roasty, full-bodied stout with enough sweetness to support the oat backbone.', 1.045, 1.065, 1.01, 1.018, 4.2, 5.9, 25, 40, 22, 40, true),
  ('Tropical Stout', 'Stout', 'A very dark, sweet, fruity, moderately strong stout with smooth, roasty flavors.', 1.056, 1.075, 1.01, 1.018, 5.5, 8, 30, 50, 30, 40, true),
  ('Foreign Extra Stout', 'Stout', 'A very dark, moderately strong, fairly dry, stout with prominent roast flavors.', 1.056, 1.075, 1.01, 1.018, 6.3, 8, 50, 70, 30, 40, true),
  ('British Strong Ale', 'Strong British Ale', 'An ale of respectable alcoholic strength, traditionally bottled-conditioned and target for cellaring.', 1.055, 1.08, 1.015, 1.022, 5.5, 8, 30, 60, 8, 22, true),
  ('Old Ale', 'Strong British Ale', 'A stronger-than-average English ale, though usually not as strong or rich as an English Barleywine.', 1.055, 1.088, 1.015, 1.022, 5.5, 9, 30, 60, 10, 22, true),
  ('Wee Heavy', 'Strong British Ale', 'Rich, sweet malt depth with caramel, toffee, and fruity flavors. Full-bodied and chewy, with warming alcohol.', 1.07, 1.13, 1.018, 1.04, 6.5, 10, 17, 35, 14, 25, true),
  ('English Barleywine', 'Strong British Ale', 'A showcase of malty richness and complex, intense flavors. Chewy and rich in body.', 1.08, 1.12, 1.018, 1.03, 8, 12, 35, 70, 8, 22, true),
  ('Blonde Ale', 'Pale American Ale', 'Easy-drinking, approachable, malt-oriented American craft beer, often with interesting fruit, hop, or character malt notes.', 1.038, 1.054, 1.008, 1.013, 3.8, 5.5, 15, 28, 3, 6, true),
  ('American Pale Ale', 'Pale American Ale', 'An average-strength, hop-forward, pale American craft beer with sufficient supporting malt.', 1.045, 1.06, 1.01, 1.015, 4.5, 6.2, 30, 50, 5, 10, true),
  ('American Amber Ale', 'Amber American Ale', 'An amber, hoppy, moderate-strength American craft beer with a malty caramel flavor.', 1.045, 1.06, 1.01, 1.015, 4.5, 6.2, 25, 40, 10, 17, true),
  ('California Common', 'Amber American Ale', 'A toasty, caramelly, hoppy, bitter, amber lager originally from the American West Coast.', 1.048, 1.054, 1.011, 1.014, 4.5, 5.5, 30, 45, 9, 14, true),
  ('American Brown Ale', 'Brown American Ale', 'A malty but hoppy standard-strength American ale frequently with chocolate and caramel flavors.', 1.045, 1.06, 1.01, 1.016, 4.3, 6.2, 20, 30, 18, 35, true),
  ('American Porter', 'Porter', 'A malty, bitter, and often somewhat hoppy dark beer with a balanced, roasted flavor.', 1.05, 1.07, 1.012, 1.018, 4.8, 6.5, 25, 50, 22, 40, true),
  ('American Stout', 'Stout', 'A fairly strong, highly roasted, bitter, hoppy dark stout.', 1.05, 1.075, 1.01, 1.022, 5, 7, 35, 75, 30, 40, true),
  ('Imperial Stout', 'Stout', 'An intensely-flavored, very strong, very dark stout with a wide range of interpretations.', 1.075, 1.115, 1.018, 1.03, 8, 12, 50, 90, 30, 40, true),
  ('American IPA', 'IPA', 'A decidedly hoppy and bitter, moderately strong, pale American ale.', 1.056, 1.07, 1.008, 1.014, 5.5, 7.5, 40, 70, 6, 14, true),
  ('Specialty IPA', 'IPA', 'A hoppy, bitter, moderately-strong American ale with flavor and aroma characteristics of specific hops.', 1.05, 1.085, 1.01, 1.018, 5.5, 9, 50, 90, 25, 40, true),
  ('Hazy IPA', 'IPA', 'An American IPA with intense fruit flavors and aromas, a soft body, smooth mouthfeel, and often opaque with substantial haze.', 1.06, 1.085, 1.01, 1.015, 6, 9, 25, 60, 3, 7, true),
  ('Double IPA', 'Strong American Ale', 'An intensely hoppy, fairly strong, bitter pale ale without the big, rich, complex maltiness of an American Barleywine.', 1.065, 1.085, 1.008, 1.018, 7.5, 10, 60, 100, 6, 14, true),
  ('American Strong Ale', 'Strong American Ale', 'A strong, full-flavored American ale that challenges and rewards the palate with full malty and hoppy flavors.', 1.062, 1.09, 1.014, 1.024, 6.3, 10, 50, 100, 7, 18, true),
  ('American Barleywine', 'Strong American Ale', 'A very strong, bitter, aromatic, and hoppy American ale with a rich malty backbone.', 1.08, 1.12, 1.016, 1.03, 8, 12, 50, 100, 9, 18, true),
  ('Wheatwine', 'Strong American Ale', 'A richly textured, high alcohol sipping beer with a significant grainy, bready flavor.', 1.08, 1.12, 1.016, 1.03, 8, 12, 30, 60, 6, 14, true),
  ('Berliner Weisse', 'European Sour Ale', 'A very pale, refreshing, low-alcohol German wheat beer with a clean lactic sourness and a very high carbonation level.', 1.028, 1.032, 1.003, 1.006, 2.8, 3.8, 3, 8, 2, 3, true),
  ('Flanders Red Ale', 'European Sour Ale', 'A sour, fruity, red wine-like Belgian-style ale with interesting supportive malt flavors and fruit complexity.', 1.048, 1.057, 1.002, 1.012, 4.6, 6.5, 10, 25, 10, 17, true),
  ('Oud Bruin', 'European Sour Ale', 'A malty, fruity, aged, somewhat sour Belgian-style brown ale.', 1.04, 1.074, 1.008, 1.012, 4, 8, 20, 25, 17, 22, true),
  ('Lambic', 'Belgian Ale', 'A fairly sour, often moderately funky, wild Belgian wheat beer with sourness taking the place of hop bitterness.', 1.04, 1.054, 1.001, 1.01, 5, 6.5, 0, 10, 3, 6, true),
  ('Gueuze', 'Belgian Ale', 'A complex, pleasantly sour but balanced wild Belgian wheat beer that is highly carbonated and very refreshing.', 1.04, 1.06, 1, 1.006, 5, 8, 0, 10, 5, 6, true),
  ('Fruit Lambic', 'Belgian Ale', 'A complex, fruity, pleasantly sour, wild wheat ale fermented by a variety of Belgian microbiota.', 1.04, 1.06, 1, 1.01, 5, 7, 0, 10, 3, 7, true),
  ('Gose', 'European Sour Ale', 'A highly-carbonated, tart and fruity wheat ale with a restrained coriander and salt character.', 1.036, 1.056, 1.006, 1.01, 4.2, 4.8, 5, 12, 3, 4, true),
  ('Witbier', 'Belgian Ale', 'A refreshing, elegant, tasty, moderate-strength wheat-based ale.', 1.044, 1.052, 1.008, 1.012, 4.5, 5.5, 8, 20, 2, 4, true),
  ('Belgian Pale Ale', 'Belgian Ale', 'A top-fermented, all malt, average strength Belgian ale that is moderately bitter with a malty profile.', 1.048, 1.054, 1.01, 1.014, 4.8, 5.5, 20, 30, 8, 14, true),
  ('Bière de Garde', 'Belgian Ale', 'A family of smooth, fairly strong, malty, lagered artisanal French beers.', 1.06, 1.08, 1.008, 1.016, 6, 8.5, 18, 28, 6, 19, true),
  ('Belgian Blond Ale', 'Belgian Ale', 'A golden, moderately-strong Belgian ale with a pleasantly subtle citrusy-spicy yeast complexity.', 1.062, 1.075, 1.008, 1.018, 6, 7.5, 15, 30, 4, 6, true),
  ('Saison', 'Belgian Ale', 'A family of refreshing, highly attenuated, hoppy, and fairly bitter Belgian ales with a very dry finish.', 1.048, 1.065, 1.002, 1.008, 5, 7, 20, 35, 5, 14, true),
  ('Belgian Golden Strong Ale', 'Strong Belgian Ale', 'A very pale, highly attenuated, strong Belgian ale that is more fruity than spicy.', 1.07, 1.095, 1.005, 1.016, 7.5, 10.5, 22, 35, 3, 6, true),
  ('Belgian Single', 'Trappist Ale', 'A blond, bitter, hoppy table beer that is very dry and highly carbonated.', 1.044, 1.054, 1.004, 1.01, 4.8, 6, 25, 45, 3, 5, true),
  ('Belgian Dubbel', 'Trappist Ale', 'A deep reddish-copper, moderately strong, malty, complex Belgian ale with rich malty flavors.', 1.062, 1.075, 1.008, 1.018, 6, 7.6, 15, 25, 10, 17, true),
  ('Belgian Tripel', 'Trappist Ale', 'A pale, somewhat spicy, dry, strong Belgian ale with a pleasant rounded malt flavor.', 1.075, 1.085, 1.008, 1.014, 7.5, 9.5, 20, 40, 4.5, 7, true),
  ('Belgian Dark Strong Ale', 'Trappist Ale', 'A dark, complex, very strong Belgian ale with a delicious blend of malt richness, dark fruit flavors, and spicy notes.', 1.075, 1.11, 1.01, 1.024, 8, 12, 20, 35, 12, 22, true),
  ('Mixed-Fermentation Sour Beer', 'Wild Specialty Beer', 'A sour and funky version of a base style of beer.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('Wild Specialty Beer', 'Wild Specialty Beer', 'A sour or funky version of a fruit, herb, or spice beer, or a wild beer aged in wood.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('Fruit Beer', 'Fruit Beer', 'A pleasant integration of fruit with beer, but still recognizable as beer.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('Fruit and Spice Beer', 'Fruit Beer', 'A appealing combination of fruit, spice, and beer.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('Specialty Fruit Beer', 'Fruit Beer', 'A fruit beer with additional ingredients or processes.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('Spice, Herb, or Vegetable Beer', 'Spiced Beer', 'An appealing fusion of spices, herbs, or vegetables and beer.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('Autumn Seasonal Beer', 'Spiced Beer', 'A malty, spiced beer that often has a moderately rich body and warming finish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('Winter Seasonal Beer', 'Spiced Beer', 'A stronger, darker, spiced beer that often has a rich body and warming finish.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('Alternative Grain Beer', 'Alternative Fermentables Beer', 'A base beer enhanced by or featuring the character of additional grain or grains.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('Alternative Sugar Beer', 'Alternative Fermentables Beer', 'A base beer enhanced by or featuring the character of additional sugar source.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('Classic Style Smoked Beer', 'Smoked Beer', 'A smoke-enhanced lager, ale, or other base style with good balance between the smoke and beer.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('Specialty Smoked Beer', 'Smoked Beer', 'A well-balanced fusion of smoke and beer with additional ingredients.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true),
  ('New Zealand Pilsner', 'New Zealand Styles', 'A pale, dry, golden-colored, cleanly-fermented beer showcasing New Zealand-type hops.', 1.044, 1.056, 1.009, 1.014, 4.5, 5.8, 25, 45, 2, 6, true)
ON CONFLICT (name) DO UPDATE SET
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  og_min = EXCLUDED.og_min,
  og_max = EXCLUDED.og_max,
  fg_min = EXCLUDED.fg_min,
  fg_max = EXCLUDED.fg_max,
  abv_min = EXCLUDED.abv_min,
  abv_max = EXCLUDED.abv_max,
  ibu_min = EXCLUDED.ibu_min,
  ibu_max = EXCLUDED.ibu_max,
  srm_min = EXCLUDED.srm_min,
  srm_max = EXCLUDED.srm_max,
  is_bjcp = EXCLUDED.is_bjcp;
