/**
 * Delivery Entity — server-safe core
 *
 * The pure-data half of the delivery entity: identity, the zod form schema,
 * state machine, relations, and AI metadata. No React imports — safe to import
 * from server route handlers and API routes.
 *
 * Groups location transfers and order fulfillments into a single delivery run.
 * A truck might restock the taproom and deliver orders on the same trip.
 *
 * Lifecycle: planned -> in_transit -> completed (or cancelled from planned/in_transit)
 * delivery_number is auto-generated by a trigger (DEL-YYYYMMDD-NNN format).
 */

import { z } from "zod";
import type { EntityCoreInput, StateMachineConfig } from "@/types/entity";
import { statesAsOptions } from "@/types/entity";

// =============================================================================
// Types
// =============================================================================

export type DeliveryView = {
  id: string;
  delivery_number: string;
  status: string;
  scheduled_date: string | null;
  ship_date: string | null;
  receive_date: string | null;
  driver_name: string | null;
  vehicle: string | null;
  notes: string | null;
  created_by: string | null;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
  // Computed fields from deliveries_with_summary view
  transfer_count: number;
  order_count: number;
  total_stops: number;
};

// =============================================================================
// State Machine
// =============================================================================

const deliveryStates = ["planned", "in_transit", "completed", "cancelled"] as const;

const deliveryTransitions: Record<string, string[]> = {
  planned: ["in_transit", "cancelled"],
  in_transit: ["completed", "cancelled"],
  completed: [],
  cancelled: [],
};

export const deliveryStateMachine: StateMachineConfig<DeliveryView> = {
  stateField: "status",
  states: [...deliveryStates],
  initialState: "planned",
  transitions: deliveryTransitions,
  stateDisplay: {
    planned: { label: "Planned", color: "default" },
    in_transit: { label: "In Transit", color: "info" },
    completed: { label: "Completed", color: "success" },
    cancelled: { label: "Cancelled", color: "error" },
  },
};

// Derive status options from state machine (single source of truth)
export const statusOptions = statesAsOptions(deliveryStateMachine);

// =============================================================================
// Zod Schema
// =============================================================================

export const deliverySchema = z.object({
  scheduled_date: z.string().nullable().optional(),
  driver_name: z.string().nullable().optional(),
  vehicle: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
});

export type DeliveryFormValues = z.infer<typeof deliverySchema>;

// =============================================================================
// Entity Core
// =============================================================================

export const deliveryCore: EntityCoreInput<DeliveryView> = {
  name: "delivery",
  table: "deliveries",
  viewTable: "deliveries_with_summary",
  displayName: "Delivery",
  displayNamePlural: "Deliveries",
  domain: "inventory",
  basePath: "/inventory/deliveries",

  defaultSort: { column: "scheduled_date", direction: "desc" },
  searchableFields: ["delivery_number", "driver_name", "vehicle"],

  detailHeader: {
    title: "delivery_number",
    badge: "status",
  },

  formSchema: deliverySchema,
  stateMachine: deliveryStateMachine,

  relations: [
    {
      name: "transfers",
      entity: "location_transfer",
      type: "hasMany",
      foreignKey: "delivery_id",
      showInDetail: true,
      detailTab: "Transfers",
    },
    {
      name: "orders",
      entity: "order",
      type: "hasMany",
      foreignKey: "delivery_id",
      showInDetail: true,
      detailTab: "Orders",
    },
  ],

  keyFields: ["delivery_number", "status", "scheduled_date", "driver_name"],
};
